services:
  - type: web
    name: flask-app
    env: python
    plan: free
    repo: https://github.com/Mini-Project-AI/server-game # replace with your repository URL
    branch: main # replace with your branch name if different from main
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
    region: frankfurt # optional, specify if you have a preferred region
