services:
  - type: web
    name: flask-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
    repo: Mini-Project-AI/server-game
    branch: main
