name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main  # Change this to your main branch name
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Change this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file name

    - name: Run tests
      run: |
        pytest  # Change this to your test command

    - name: Set PR status
      if: always()  # Always run this step, even if previous steps fail
      uses: actions/github-script@v4
      with:
        script: |
          const { context, GitHub } = require('@actions/github');
          const github = new GitHub(process.env.GITHUB_TOKEN);
          const status = process.env.GITHUB_RUN_CONCLUSION === 'success' ? 'completed' : 'completed';
          const conclusion = process.env.GITHUB_RUN_CONCLUSION === 'success' ? 'success' : 'failure';
          await github.checks.create({
            ...context.repo,
            head_sha: context.sha,
            name: 'CI/CD Pipeline',
            status: status,
            conclusion: conclusion,
            output: {
              title: 'Test Results',
              summary: process.env.GITHUB_RUN_CONCLUSION === 'success' ? 'All tests passed' : 'Tests failed'
            }
          });
