name: Add PR Template

on:
  pull_request:
    types: [opened]

jobs:
  add-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR Template exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/.github/PULL_REQUEST_TEMPLATE.md" ]; then
            cp .github/PULL_REQUEST_TEMPLATE.md $GITHUB_WORKSPACE/.github/PULL_REQUEST_TEMPLATE.md
          else
            echo "PR Template already exists. Skipping copying."
          fi
