name: Add PR Template

on:
  pull_request:
    types: [opened]

jobs:
  add-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add Pull Request Template
        run: |
          cp .github/PULL_REQUEST_TEMPLATE.md $GITHUB_WORKSPACE/.github/PULL_REQUEST_TEMPLATE.md
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Add PR Template" || true
          git push
